# Generated by Django 5.1.4 on 2025-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('size', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField(default=False, help_text='Age = 18+')),
                ('buyer', models.ManyToManyField(to='task1.buyer')),
            ],
        ),
    ]
